name: check-secrets-action
author: mattdavis0351
description: validation action for this lab

inputs:
  my-github-pat:
    description: Github PAT
    required: true
  secrets-context:
    description: The GitHub Actions secrets context object
    required: true

runs:
  using: node12
  main: "dist/index.js"
